export const leadData = [
    {
        id: 0,
        image: "SREEMOYEE DUTTA.jpeg",
        igLink: "https://www.instagram.com/dutta.sreemoyee?igsh=cWZvbGNsZG1vMzBn",
        linkedinLink: "google.com",
        name: "Sreemoyee Dutta",
        position: "Coordinator",
    },
    {
        id: 1,
        image: "Emmanuel Anthony Francis.jpg",
        igLink: "https://www.instagram.com/lilemmu301?igsh=N3p4M3FpMG00d2tk",
        linkedinLink: "google.com",
        name: "Emmanuel Anthony Francis",
        position: "Coordinator",
    },
    {
        id: 2,
        image: "Haldar.jpg",
        igLink: "https://www.instagram.com/enjoywithhengla?igsh=MXRkdHVzczlyMGd5NQ",
        linkedinLink: "google.com",
        name: "Swarnak haldar",
        position: "Assistant Coordinator",
    },
    {
        id: 3,
        image: "Argha Dey.jpg",
        igLink: "https://www.instagram.com/aj_argha?igsh=amcyOXMwYzliZWJw",
        linkedinLink: "google.com",
        name: "Argha Dey",
        position: "Assistant Coordinator",
    },
    {
        id: 4,
        image: "ANIKET_MONDAL.jpg",
        igLink: "https://www.instagram.com/dr.co_cktail?igsh=Ym5xOHJpejVldjls",
        linkedinLink: "google.com",
        name: "Aniket Mandal",
        position: "Assistant Coordinator",
    },
    {
        id: 5,
        image: "Amol Kshitij.JPG",
        igLink: "https://www.instagram.com/amol_kshitij/",
        linkedinLink: "google.com",
        name: "Amol Kshitij",
        position: "Inaugral & Logistics Head",
    },
    {
        id: 6,
        image: "SARVAGYA.jpg",
        igLink: "https://www.instagram.com/sarvagya_singh?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==",
        linkedinLink: "google.com",
        name: "Sarvagya Singh",
        position: "Marketing & PR Head",
    },
    {
        id: 7,
        image: "Prabir Nayak.jpeg",
        igLink: "https://www.instagram.com/prabir_2011?igsh=MWJyd3RkaTJheDk4Zg==",
        linkedinLink: "google.com",
        name: "Prabir Nayak",
        position: "Operations Head",
    },

    {
        id: 8,
        image: "Aditya Bhardwaj.jpg",
        igLink: "https://www.instagram.com/lonepair.4?igsh=MXYxb2RoNzByYXh1Yw==",
        linkedinLink: "google.com",
        name: "Aditya Bhardwaj",
        position: "Web Dev Head",
    },
    // {
    //     id: 10,
    //     image: "Aryan Tripathi.jpg",
    //     igLink: "google.com",
    //     linkedinLink: "google.com",
    //     name: "Aryan Tripathi",
    //     position: "Online Marketing Lead",
    // },
    {
        id: 9,
        image: "Bramhajeet Behera.jpg",
        igLink: "https://www.instagram.com/bramhajeetbehera?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==",
        linkedinLink: "google.com",
        name: "Bramhajeet Behera",
        position: "Sponsorship Lead",
    },
    {
        id: 10,
        image: "Aryan Tripathi.jpg",
        igLink: "https://www.instagram.com/aryann_.tripathi?igsh=NDN5Y2hwNXN3bW83",
        linkedinLink: "google.com",
        name: "Aryan Tripathi",
        position: "Online Marketing Lead",
    },
    // {
    //     id: 8,
    //     image: "Aditya Bhardwaj.jpg",
    //     igLink: "google.com",
    //     linkedinLink: "google.com",
    //     name: "Aditya Bhardwaj",
    //     position: "Web Designer",
    // },

    {
        id: 11,
        image: "Dipayan Saha.jpg",
        igLink: "https://www.instagram.com/._diipaayyong._?igsh=aGo3NXkxOGlwdHQ2",
        linkedinLink: "google.com",
        name: "Dipayan Saha",
        position: "Offline Maketing Lead",
    },
];